spring.application.name=api
server.port = 8090
spring.datasource.url=jdbc:postgresql://${HOSTNAME}:${PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.hibernate.ddl-auto=update
jwt.secret=D61294BF2DB99399AB2DD6D09D3893C92B79A996A66C435C03DE1E130194CBC9
jwt.expiration=3600000